import { MONITORED_ZONE } from "@/lib/constants";
import type { ProviderRunLog } from "@/lib/scrapers/providers/types";
import type { NormalizedListing } from "@/types";

const HOUR = 60 * 60 * 1000;
const DAY = 24 * HOUR;
const MINUTE = 60 * 1000;

let lastRunLog: ProviderRunLog | null = null;

function isoFromNow(offsetMs: number) {
  return new Date(Date.now() - offsetMs).toISOString();
}

export const mockProvider = {
  name: "mock",
  async fetchListings(): Promise<NormalizedListing[]> {
    const listings: NormalizedListing[] = [
      {
        id: "fbb16567-5c33-44e8-a5b2-6b714cb8a001",
        source: "Subito",
        sourceListingId: "SBT-1001",
        url: "https://example.com/subito/bitonto-via-traiana-1001",
        canonicalUrl: "https://example.com/subito/bitonto-via-traiana-1001",
        title: "Bilocale ristrutturato con balcone in Via Traiana",
        description:
          "Privato vende bilocale luminoso vicino al centro. Prezzo trattabile. No agenzie.",
        price: 128000,
        sqm: 82,
        rooms: 2.5,
        floor: "2",
        zone: `${MONITORED_ZONE} - Via Traiana`,
        addressRaw: "Via Traiana, Bitonto",
        sellerType: "private",
        sellerName: "Francesco P.",
        phone: "3285550101",
        portalDeclaredDate: isoFromNow(1 * DAY),
        metadataDatePublished: isoFromNow(14 * HOUR),
        metadataDateModified: isoFromNow(5 * HOUR),
        firstSeenAt: isoFromNow(4 * HOUR),
        lastSeenAt: isoFromNow(1 * HOUR),
        checkedAt: new Date().toISOString(),
        status: "new",
        note: "Profilo da monitorare in giornata: annuncio fresco e diretto.",
        rawPayload: { label: "private-new", mock: true },
      },
      {
        id: "fbb16567-5c33-44e8-a5b2-6b714cb8a002",
        source: "Immobiliare.it",
        sourceListingId: "IMM-2307",
        url: "https://example.com/immobiliare/bitonto-corso-vittorio-2307",
        canonicalUrl: "https://example.com/immobiliare/bitonto-corso-vittorio-2307",
        title: "Trilocale con box auto in Corso Vittorio Emanuele",
        description:
          "Incarico agenzia, piano medio con doppia esposizione e box auto.",
        price: 189000,
        sqm: 108,
        rooms: 3,
        floor: "3",
        zone: `${MONITORED_ZONE} - Centro`,
        addressRaw: "Corso Vittorio Emanuele, Bitonto",
        sellerType: "agency",
        sellerName: "Agenzia Levante Casa",
        phone: "0805551200",
        portalDeclaredDate: isoFromNow(18 * DAY),
        metadataDatePublished: isoFromNow(19 * DAY),
        metadataDateModified: isoFromNow(3 * DAY),
        firstSeenAt: isoFromNow(18 * DAY),
        lastSeenAt: isoFromNow(2 * HOUR),
        checkedAt: new Date().toISOString(),
        status: "watch",
        rawPayload: { label: "agency", mock: true },
      },
      {
        id: "fbb16567-5c33-44e8-a5b2-6b714cb8a003",
        source: "Casa.it",
        sourceListingId: "CASA-9841",
        url: "https://example.com/casa/bitonto-san-valentino-9841",
        canonicalUrl: "https://example.com/casa/bitonto-san-valentino-9841",
        title: "Appartamento con terrazzo in zona San Valentino",
        description:
          "Privato vende ampio appartamento con terrazzo e cantina, pronto da abitare.",
        price: 145000,
        sqm: 104,
        rooms: 3,
        floor: "1",
        zone: `${MONITORED_ZONE} - San Valentino`,
        addressRaw: "Zona San Valentino, Bitonto",
        sellerType: "private",
        sellerName: "Michele R.",
        phone: "3334087612",
        portalDeclaredDate: isoFromNow(92 * DAY),
        metadataDatePublished: isoFromNow(91 * DAY),
        metadataDateModified: isoFromNow(8 * DAY),
        firstSeenAt: isoFromNow(90 * DAY),
        lastSeenAt: isoFromNow(3 * HOUR),
        checkedAt: new Date().toISOString(),
        status: "review",
        note: "Vecchio annuncio da verificare manualmente: possibile apertura alla trattativa.",
        rawPayload: { label: "private-90-days", mock: true },
      },
      {
        id: "fbb16567-5c33-44e8-a5b2-6b714cb8a004",
        source: "Idealista",
        sourceListingId: "IDL-4402",
        url: "https://example.com/idealista/bitonto-via-ammiraglio-4402",
        canonicalUrl: "https://example.com/idealista/bitonto-via-ammiraglio-4402",
        title: "Quadrivani con veranda e cantinola",
        description:
          "Privato propone quadrivani panoramico con veranda. Prezzo trattabile.",
        price: 162000,
        sqm: 118,
        rooms: 4,
        floor: "4",
        zone: `${MONITORED_ZONE} - Via Ammiraglio Vacca`,
        addressRaw: "Via Ammiraglio Vacca, Bitonto",
        sellerType: "private",
        sellerName: "Giuseppe T.",
        phone: "3492299988",
        portalDeclaredDate: isoFromNow(74 * DAY),
        metadataDatePublished: isoFromNow(74 * DAY),
        metadataDateModified: isoFromNow(2 * DAY),
        firstSeenAt: isoFromNow(72 * DAY),
        lastSeenAt: isoFromNow(2 * HOUR),
        checkedAt: new Date().toISOString(),
        status: "review",
        previousPrice: 175000,
        rawPayload: { label: "price-drop", mock: true },
      },
      {
        id: "fbb16567-5c33-44e8-a5b2-6b714cb8a005",
        source: "Bakeca",
        sourceListingId: "BK-772",
        url: "https://example.com/bakeca/bitonto-via-berardi-772",
        canonicalUrl: "https://example.com/bakeca/bitonto-via-berardi-772",
        title: "Casa indipendente rifinita nel borgo antico",
        description:
          "Annuncio ripubblicato con foto simili. No agenzie. Ottimo investimento nel centro storico.",
        price: 97000,
        sqm: 88,
        rooms: 3,
        floor: "terra-cielo",
        zone: `${MONITORED_ZONE} - Borgo Antico`,
        addressRaw: "Via Berardi, Bitonto",
        sellerType: "private",
        sellerName: "Rita C.",
        phone: "3476110021",
        portalDeclaredDate: isoFromNow(133 * DAY),
        metadataDatePublished: isoFromNow(5 * DAY),
        metadataDateModified: isoFromNow(1 * DAY),
        firstSeenAt: isoFromNow(122 * DAY),
        lastSeenAt: isoFromNow(30 * MINUTE),
        checkedAt: new Date().toISOString(),
        status: "watch",
        isRepublishedSuspected: true,
        previousUrls: [
          "https://example.com/bakeca/bitonto-via-berardi-old-601",
          "https://example.com/subito/bitonto-via-berardi-old-198",
        ],
        rawPayload: { label: "suspected-republished", mock: true },
      },
      {
        id: "fbb16567-5c33-44e8-a5b2-6b714cb8a006",
        source: "Subito",
        sourceListingId: "SBT-1019",
        url: "https://example.com/subito/bitonto-mariotto-1019",
        canonicalUrl: "https://example.com/subito/bitonto-mariotto-1019",
        title: "Deposito con cambio d'uso possibile a Mariotto",
        description:
          "Contatto non verificato, pochi dettagli e pubblicazione essenziale.",
        price: 54000,
        sqm: 75,
        rooms: 2,
        floor: "terra",
        zone: `${MONITORED_ZONE} - Mariotto`,
        addressRaw: "Mariotto, Bitonto",
        sellerType: "unknown",
        sellerName: null,
        phone: null,
        portalDeclaredDate: isoFromNow(11 * DAY),
        metadataDatePublished: isoFromNow(11 * DAY),
        metadataDateModified: isoFromNow(2 * DAY),
        firstSeenAt: isoFromNow(10 * DAY),
        lastSeenAt: isoFromNow(90 * MINUTE),
        checkedAt: new Date().toISOString(),
        status: "review",
        rawPayload: { label: "unknown", mock: true },
      },
      {
        id: "fbb16567-5c33-44e8-a5b2-6b714cb8a007",
        source: "Immobiliare.it",
        sourceListingId: "IMM-2914",
        url: "https://example.com/immobiliare/bitonto-piazza-cavour-2914",
        canonicalUrl: "https://example.com/immobiliare/bitonto-piazza-cavour-2914",
        title: "Attico signorile con vista su Piazza Cavour",
        description:
          "Agenzia propone attico ristrutturato con terrazza, finiture premium e doppio posto auto.",
        price: 368000,
        sqm: 155,
        rooms: 5,
        floor: "5",
        zone: `${MONITORED_ZONE} - Piazza Cavour`,
        addressRaw: "Piazza Cavour, Bitonto",
        sellerType: "agency",
        sellerName: "Studio Habitat",
        phone: "0801122334",
        portalDeclaredDate: isoFromNow(35 * DAY),
        metadataDatePublished: isoFromNow(35 * DAY),
        metadataDateModified: isoFromNow(4 * DAY),
        firstSeenAt: isoFromNow(34 * DAY),
        lastSeenAt: isoFromNow(2 * HOUR),
        checkedAt: new Date().toISOString(),
        status: "watch",
        rawPayload: { label: "expensive-apartment", mock: true },
      },
      {
        id: "fbb16567-5c33-44e8-a5b2-6b714cb8a008",
        source: "Casa.it",
        sourceListingId: "CASA-9910",
        url: "https://example.com/casa/bitonto-lamione-9910",
        canonicalUrl: "https://example.com/casa/bitonto-lamione-9910",
        title: "Casa indipendente economica con piccolo cortile",
        description:
          "Privato vende soluzione indipendente da personalizzare, prezzo trattabile e nessuna intermediazione.",
        price: 79000,
        sqm: 96,
        rooms: 3,
        floor: "terra-cielo",
        zone: `${MONITORED_ZONE} - Via Lamione`,
        addressRaw: "Via Lamione, Bitonto",
        sellerType: "private",
        sellerName: "Anna L.",
        phone: "3207781540",
        portalDeclaredDate: isoFromNow(67 * DAY),
        metadataDatePublished: isoFromNow(67 * DAY),
        metadataDateModified: isoFromNow(6 * DAY),
        firstSeenAt: isoFromNow(66 * DAY),
        lastSeenAt: isoFromNow(45 * MINUTE),
        checkedAt: new Date().toISOString(),
        status: "watch",
        rawPayload: { label: "cheap-independent-house", mock: true },
      },
    ];

    lastRunLog = {
      provider: "mock",
      searchUrls: [],
      foundUrls: listings.length,
      detailPagesRead: 0,
      errors: [],
    };

    return listings;
  },
  getLastRunLog() {
    return lastRunLog;
  },
};
