import { icon } from "./icons.js";
export function unitHistoryHtml(unit, escape, date) {
  const memory = unit.memory;
  if (!memory) return "";
  const stages = { queued: "Preparazione", planned: "Piano", people_resolved: "Identità degli intestatari", people_synced: "Anagrafiche", property_resolved: "Identità dell’immobile", property_synced: "Dati dell’immobile", ownerships_synced: "Proprietà e quote", verified: "Verifica dei dati", activity_synced: "Attività", completed: "Import completo" };
  const labels = { acquired: "Dati acquisiti", compared: "Confronto CRM", corrected: "Correzione manuale", import_started: "Import avviato / ripreso", stage_completed: "Passaggio conservato", retry_scheduled: "Tentativo ripetuto", import_paused: "Import sospeso", import_quarantined: "Import non concluso", import_completed: "Import verificato", street_associated: "Via associata" };
  const s = memory.statistics;
  return `<p class="unit-memory-stats">${s.acquisitions} ${s.acquisitions === 1 ? "acquisizione" : "acquisizioni"} · ${s.verifiedImports} ${s.verifiedImports === 1 ? "import verificato" : "import verificati"}${s.retries ? ` · ${s.retries} tentativi ripetuti` : ""}</p><details data-disclosure="${escape(unit.key)}:lifecycle"><summary>Storico dell’immobile (${memory.events.length})</summary>${memory.incompleteHistory ? '<p class="explanation">Lo storico precedente contiene solo i passaggi documentati. Le operazioni mancanti non vengono ricostruite.</p>' : ""}<ol class="unit-timeline">${[...memory.events].reverse().map(e => `<li><strong class="icon-label">${icon({ acquired: "download", compared: "search", corrected: "pencil", import_completed: "check", import_paused: "pause", import_quarantined: "warning", street_associated: "link" }[e.kind] || "history")}${escape(labels[e.kind] || "Operazione conservata")}</strong><p class="meta">${e.at ? date(e.at) : "Data originale non disponibile"}${e.recovered ? " · recuperato dallo storico" : ""}${e.stage ? ` · ${escape(stages[e.stage] || "Passaggio import")}` : ""}</p><p>${escape(e.message)}</p>${e.crmId ? `<p class="mono">Scheda CRM ${escape(e.crmId)}</p>` : ""}${e.source ? `<details><summary>Dati conservati in questa operazione</summary><p>${escape(e.source.fullAddress)} · ${escape(e.source.category)}</p>${e.source.owners.map(o => `<p>${escape(o.fullName)} · ${escape(o.taxCode)} · quota ${escape(o.sharePercentage ?? "?")}%</p>`).join("")}${e.note ? `<p>${escape(e.note)}</p>` : ""}</details>` : ""}${e.syncedPeople?.length ? `<details><summary>Intestatari verificati (${e.syncedPeople.length})</summary>${e.syncedPeople.map(p => `<p class="mono">${escape(p.taxCode)}: ${p.mergePerformed ? "duplicati uniti e verificati" : "anagrafica verificata"} · CRM ${escape(p.crmPersonId)}</p>`).join("")}</details>` : ""}${e.activity ? `<p class="meta">Attività: ${escape({ created: "creata e riletta", existing: "già presente e verificata", disabled: "non prevista" }[e.activity.outcome])}${e.activity.activityId ? ` · ${escape(e.activity.activityId)}` : ""}</p>` : ""}<p class="meta">Operazione ${escape(e.runId.replace(/^history:/, "").slice(0, 8))}</p></li>`).join("")}</ol></details>`;
}
