const STEPS = ["ready","sister_results_acquired","properties_extracted","owners_extracted","data_normalized","acquisition_reviewed","properties_processed","verified","completed"];
const PHASES = [
  { key:"prepare", label:"Preparazione", detail:"Apro e controllo i collegamenti" },
  { key:"read", label:"Leggo tutti i dati", detail:"Immobili, proprietari e quote da SISTER" },
  { key:"review", label:"Ti mostro il riepilogo", detail:"Controlli tutto prima di proseguire" },
  { key:"work", label:"Completo un immobile alla volta", detail:"Proprietario, immobile, attività, recapiti e comproprietari" },
  { key:"finish", label:"Controllo e termino", detail:"Verifico che non manchi nulla" },
];
const GUIDE = {
  ready:{label:"Preparazione",doing:"Controllo che Chrome, SISTER, gestionale ed Excel siano raggiungibili.",next:"Quando tutto è pronto, ti chiederò di acquisire i risultati SISTER."},
  sister_results_acquired:{label:"Lettura SISTER",doing:"Sto leggendo la pagina dei risultati che hai già aperto.",next:"Individuerò solo gli immobili delle categorie A/ e C/."},
  properties_extracted:{label:"Raccolta immobili",doing:"Sto raccogliendo foglio, particella, subalterno, indirizzo e dati catastali.",next:"Per ogni immobile aprirò l’elenco dei proprietari."},
  owners_extracted:{label:"Raccolta proprietari",doing:"Sto leggendo nominativi, codici fiscali, diritti e quote di proprietà.",next:"Escluderò automaticamente i diritti diversi dalla Proprietà."},
  data_normalized:{label:"Controllo dati",doing:"Sto uniformando codici fiscali, quote e chiavi catastali per evitare duplicati.",next:"Ti mostrerò un riepilogo completo prima del confronto col gestionale."},
  acquisition_reviewed:{label:"Riepilogo acquisizione",doing:"I dati SISTER sono raccolti. Attendo il tuo controllo del riepilogo.",next:"Dopo la conferma completerò il primo immobile con tutti i suoi proprietari, poi passerò al successivo."},
  properties_processed:{label:"Lavorazione degli immobili",doing:"Completo un immobile alla volta, senza separare persone, immobili e quote in lavorazioni diverse.",next:"Per questo immobile seguo sempre lo stesso ordine: proprietario principale, immobile, attività, recapiti, comproprietari e quote."},
  person_searched:{label:"Ricerca nominativi",doing:"Cerco ogni persona nel gestionale prima per codice fiscale, poi per telefono e anagrafica.",next:"Se non esiste, preparerò una nuova scheda; se esiste, completerò solo i dati mancanti."},
  person_created_or_updated:{label:"Aggiornamento nominativi",doing:"Sto creando o aggiornando le schede delle persone senza duplicare i recapiti.",next:"Controllerò eventuali unioni proposte dal gestionale."},
  person_merge_reviewed:{label:"Controllo unioni",doing:"Verifico che gli eventuali merge del gestionale siano conclusi senza conflitti.",next:"Aprirò gli immobili collegati ai nominativi."},
  property_searched:{label:"Ricerca immobili",doing:"Cerco l’immobile dentro la scheda del proprietario, confrontando prima dati catastali e poi via e civico.",next:"Se lo trovo aggiorno i dati; altrimenti preparo una nuova scheda immobile."},
  property_created_or_updated:{label:"Aggiornamento immobili",doing:"Sto completando i dati catastali dell’immobile usando SISTER come fonte principale.",next:"Creerò una sola attività direttamente dalla scheda dell’immobile."},
  activity_created:{label:"Attività sugli immobili",doing:"Sto aggiungendo l’attività “Da eseguire” dalla scheda di ciascun immobile, non dal cliente.",next:"Poi abbinerò i recapiti del file Excel."},
  contacts_matched:{label:"Recapiti Excel",doing:"Cerco il codice fiscale nel file Excel e raccolgo telefoni ed email senza duplicati.",next:"Aggiungerò i recapiti mancanti alle persone già individuate."},
  owners_linked:{label:"Comproprietari",doing:"Sto collegando ogni immobile a tutti i proprietari e verificando le quote.",next:"Eseguirò l’ultimo controllo di completezza."},
  verified:{label:"Verifica finale",doing:"Controllo che immobili, persone, attività, recapiti e quote siano stati elaborati.",next:"Se non manca nulla, il lavoro sarà concluso."},
  completed:{label:"Completato",doing:"La lavorazione è terminata e tutti i passaggi risultano salvati.",next:"Puoi aprire i dettagli oppure iniziare una nuova lavorazione."},
};
const ERROR_STATES=new Set(["needs_review","session_expired","portal_error","data_incomplete","failed"]);
let appState=null,checks=[],selectedMode="assisted",toastTimer=null,pendingCancelJobId=null,cancelInFlight=false,resolutionDetail=null,resolutionJobId=null;
const $=id=>document.getElementById(id);
const esc=value=>String(value??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[c]);
const fmtTime=value=>value?new Intl.DateTimeFormat("it-IT",{hour:"2-digit",minute:"2-digit"}).format(new Date(value)):"—";
const fmtDate=value=>value?new Intl.DateTimeFormat("it-IT",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}).format(new Date(value)):"—";
const guide=step=>GUIDE[step]??{label:String(step??"Elaborazione").replaceAll("_"," "),doing:"Il programma sta completando questo passaggio.",next:"L’avanzamento sarà salvato automaticamente."};
function toast(message){const el=$("toast");el.textContent=message;el.classList.add("is-visible");clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove("is-visible"),3500)}

function errorAdvice(job,error){const text=String(error??job?.error_message??"").toLowerCase();const status=job?.status;
  if(status==="session_expired"||text.includes("sessione")&&text.includes("scad"))return{cause:"La sessione del portale non è più valida.",steps:["Apri Chrome di lavoro.","Accedi di nuovo al portale indicato, senza chiudere la scheda.","Torna qui e premi “Ho effettuato l’accesso, riprendi”."],action:"session"};
  if(status==="data_incomplete"||text.includes("mancant")||text.includes("quota"))return{cause:"Uno o più dati indispensabili non sono disponibili o non sono leggibili con certezza.",steps:["Apri “Correggi dati qui sotto”.","Compila i campi evidenziati usando il dato visibile su SISTER.","Salva e riprendi: il programma continuerà dal passaggio successivo."],action:"data"};
  if(status==="needs_review"||text.includes("più")||text.includes("merge"))return{cause:"Il programma ha trovato più possibilità e non vuole scegliere quella sbagliata.",steps:["Controlla nel gestionale quale scheda è corretta.","Se serve, completa il merge o la scelta manualmente.","Premi “Ho risolto nel gestionale, riprendi”."],action:"review"};
  if(text.includes("selector")||text.includes("locator")||text.includes("pagina")||status==="portal_error")return{cause:"La pagina del portale è diversa da quella attesa oppure c’è una finestra aperta che copre i comandi.",steps:["Lascia aperta la pagina indicata nel gestionale o in SISTER.","Chiudi eventuali messaggi o finestre rimaste a metà.","Premi “Riprova questo passaggio”. Se manca un valore, puoi inserirlo dall’app."],action:"portal"};
  return{cause:"Si è verificato un problema inatteso, ma l’avanzamento precedente è al sicuro.",steps:["Premi “Controlla collegamenti”.","Se tutti i controlli sono verdi, riprova il passaggio.","Se manca un dato, usa “Correggi dati qui sotto”."],action:"unknown"};
}

function renderChecks(){const wanted=[["chrome","Chrome"],["sister","SISTER"],["crm","Gestionale"],["excel","File Excel"],["supabase","Archivio dati"]];$("checksGrid").innerHTML=wanted.map(([id,label])=>{const keep=appState?.sisterKeepAlive;const keepResult=id==="sister"&&!["waiting","disabled"].includes(keep?.statusLabel)?{ok:keep.ok,detail:keep.ok?`Sessione attiva · ${fmtTime(keep.checkedAt)}`:keep.message}:null;const result=keepResult??checks.find(x=>x.id===id);return`<div class="check-item ${result?(result.ok?"is-ok":"is-error"):""}"><span></span><div><b>${label}</b><small title="${esc(result?.detail??"Da controllare")}">${esc(result?.detail??"Da controllare")}</small></div></div>`}).join("")}
function currentPhase(step){if(step==="ready")return 0;if(["sister_results_acquired","properties_extracted","owners_extracted","data_normalized"].includes(step))return 1;if(step==="acquisition_reviewed")return 2;if(step==="properties_processed"||["person_searched","person_created_or_updated","person_merge_reviewed","property_searched","property_created_or_updated","activity_created","contacts_matched","owners_linked"].includes(step))return 3;return 4}
function nextStepName(last){const index=STEPS.indexOf(last);return index<0?"properties_processed":STEPS[Math.min(index+1,STEPS.length-1)]}
function renderSteps(){const job=appState?.jobs?.find(j=>j.id===appState.activeJobId);const current=appState?.currentStep??job?.current_step??"ready",phase=currentPhase(current),done=current==="completed";let percent=[0,15,40,50,95][phase]??0;const p=appState?.propertyProgress;if(current==="properties_processed"&&p?.total)percent=Math.round(50+((p.index-1+(p.stage==="completed"?1:0))/p.total)*40);if(done)percent=100;$("progressPercent").textContent=`${percent}%`;$("progressBar").style.width=`${percent}%`;$("workflowSteps").innerHTML=PHASES.map((item,i)=>`<li class="workflow-step ${done||i<phase?"is-done":i===phase?"is-current":""}"><span class="index">${done||i<phase?"✓":i+1}</span><b>${esc(item.label)}<small>${esc(item.detail)}</small></b></li>`).join("")}
function cancelButton(jobId){return jobId?`<button class="button danger" data-cancel-job="${esc(jobId)}">Annulla lavoro</button>`:""}
function promptButtons(prompt){if(prompt.kind==="merge")return`<button class="button primary" data-prompt="confirm">Il merge è corretto</button><button class="button secondary" data-prompt="manual">Lo sistemo manualmente</button>`;if(prompt.kind==="decision")return`<button class="button primary" data-prompt="confirm">Conferma</button><button class="button secondary" data-prompt="skip">Salta questo caso</button><button class="button secondary" data-prompt="manual">Modifico nel gestionale</button><button class="button danger" data-prompt="review">Segna da verificare</button>`;return`<button class="button primary" data-prompt="confirm">${prompt.kind==="acquisition"?"Acquisisci risultati":"Ho terminato, continua"}</button>`}
function renderAction(){const panel=$("actionPanel"),job=appState?.jobs?.find(j=>j.id===appState.activeJobId);
  if(appState?.configError){panel.className="now-card is-error";panel.innerHTML=`<div class="now-grid"><div class="now-main"><div class="now-label"><span></span>Configurazione necessaria</div><h2>Completa una sola volta le impostazioni</h2><p>Il programma non ha trovato la configurazione interna. Non serve creare un file: inserisci i valori nella sezione avanzata e Windows li proteggerà.</p><div class="now-actions"><button class="button primary" data-action="config">Apri impostazioni</button></div></div><div class="now-side"><h3>Cosa manca</h3><p>${esc(appState.configError)}</p></div></div>`;return}
  if(appState?.cancellingJobId){panel.className="now-card is-warning";panel.innerHTML=`<div class="now-grid"><div class="now-main"><div class="now-label"><span></span>Arresto sicuro</div><h2>Sto annullando la lavorazione</h2><p>Attendo la fine dell’operazione già iniziata, poi elimino i dati del lavoro.</p></div><div class="now-side"><b>Non chiudere l’app.</b><p>Ti avviserò appena l’annullamento è concluso.</p></div></div>`;return}
  if(appState?.prompt){if(appState.prompt.kind==="acquisition-review"){panel.className="now-card";panel.innerHTML=`<div class="now-grid"><div class="now-main"><div class="now-label"><span></span>Dati raccolti</div><h2>Controlla immobili e proprietari</h2><p>La raccolta da SISTER è finita. Prima di toccare il gestionale, verifica il riepilogo.</p><div class="now-actions"><button class="button primary" data-action="open-review">Apri il riepilogo</button>${cancelButton(appState.activeJobId)}</div></div><div class="now-side"><h3>Dopo la conferma</h3><p>Inizierò a cercare i nominativi nel gestionale.</p></div></div>`;return}panel.className="now-card is-warning";panel.innerHTML=`<div class="now-grid"><div class="now-main"><div class="now-label"><span></span>Serve una tua conferma</div><h2>${esc(appState.prompt.title)}</h2><p>${esc(appState.prompt.summary)}</p><div class="now-actions">${promptButtons(appState.prompt)}${cancelButton(appState.activeJobId)}</div></div><div class="now-side"><h3>Perché mi sono fermato?</h3><p>Questa scelta può modificare dati nel gestionale. Attendo la tua decisione per sicurezza.</p></div></div>`;return}
  if(appState?.lastError){const advice=errorAdvice(job,appState.lastError),last=guide(job?.last_completed_step),next=guide(nextStepName(job?.last_completed_step));panel.className="now-card is-error";panel.innerHTML=`<div class="now-grid"><div class="now-main"><div class="now-label"><span></span>Lavorazione ferma, dati salvati</div><h2>${esc(advice.cause)}</h2><p>Ultimo punto concluso: <b>${esc(last.label)}</b>. Ripartirò da <b>${esc(next.label)}</b>, senza ricominciare.</p><div class="recovery-box"><b>Cosa fare adesso</b><ol>${advice.steps.map(x=>`<li>${esc(x)}</li>`).join("")}</ol></div><div class="now-actions">${advice.action==="data"||advice.action==="unknown"||advice.action==="portal"?`<button class="button primary" data-action="open-corrections">Correggi dati qui sotto</button>`:""}<button class="button ${advice.action==="data"?"secondary":"primary"}" data-action="resume-current">${advice.action==="session"?"Ho effettuato l’accesso, riprendi":advice.action==="review"?"Ho risolto nel gestionale, riprendi":"Riprova questo passaggio"}</button><button class="button secondary" data-action="checks">Controlla collegamenti</button>${cancelButton(appState.activeJobId)}</div><details class="technical-details"><summary>Mostra il dettaglio tecnico</summary><pre>${esc(appState.lastError)}</pre></details></div><div class="now-side"><h3>Il lavoro è al sicuro</h3><p>Ogni passaggio concluso è stato salvato. Riprendendo non verranno riletti o duplicati i dati già completati.</p></div></div>`;return}
  const current=guide(appState?.currentStep??"ready");if(appState?.active){const progress=appState.propertyProgress;const propertyContext=appState.currentStep==="properties_processed"&&progress?`<span class="property-position">Immobile ${progress.index} di ${progress.total}</span><h2>${esc(progress.address??"Immobile senza indirizzo")}</h2><p><b>${esc(progress.message)}</b></p>`:`<h2>${esc(current.label)}</h2><p>${esc(current.doing)}</p>`;panel.className="now-card";panel.innerHTML=`<div class="now-grid"><div class="now-main"><div class="now-label"><span></span>Sto lavorando adesso</div>${propertyContext}<div class="now-actions"><button class="button secondary" data-action="pause">Metti in pausa</button>${cancelButton(appState.activeJobId)}</div></div><div class="now-side"><h3>${progress?"Ordine per questo immobile":"Cosa succede dopo"}</h3>${progress?"<ol><li>Proprietario principale</li><li>Immobile collegato</li><li>Attività dall’immobile</li><li>Recapiti Excel</li><li>Comproprietari e quote</li></ol>":`<p>${esc(current.next)}</p>`}<p><b>Non devi fare nulla</b> finché non compare una richiesta.</p></div></div>`;return}
  panel.className="now-card";panel.innerHTML=`<div class="now-grid"><div class="now-main"><div class="now-label"><span></span>Pronto per iniziare</div><h2>Apri le due schede nel Chrome di lavoro</h2><p>Accedi manualmente a SISTER e al gestionale. Su SISTER scegli Comune, via e civico, poi avvia la ricerca e lascia visibili i risultati.</p><div class="now-actions"><button class="button primary" data-action="checks">Controlla se è tutto pronto</button></div></div><div class="now-side"><h3>In tre mosse</h3><ol><li>Apri Chrome di lavoro.</li><li>Porta SISTER sui risultati.</li><li>Premi “Inizia lavorazione”.</li></ol></div></div>`}

function renderJobs(){const jobs=appState?.jobs??[];$("jobCount").textContent=jobs.length;$("jobsList").innerHTML=jobs.length?jobs.map(job=>{const resumable=job.status!=="completed"&&(!appState.active||job.id!==appState.activeJobId),place=[job.municipality,job.street,job.civic_number].filter(Boolean).join(" · ")||`Lavoro ${job.id.slice(0,8)}`,tone=job.status==="completed"?"is-completed":ERROR_STATES.has(job.status)?"is-error":job.status==="running"?"is-running":"";return`<article class="job-item ${tone}"><span></span><div><b>${esc(place)}</b><small>${job.mode==="automatic"?"Automatica":"Guidata"} · ultimo punto: ${esc(guide(job.last_completed_step??"ready").label)} · ${fmtDate(job.updated_at??job.created_at)}${job.error_message?`<br><span class="job-issue">Richiede attenzione: ${esc(job.error_message)}</span>`:""}</small></div><div class="job-actions"><button class="text-button" data-detail-job="${job.id}">Apri</button>${ERROR_STATES.has(job.status)?`<button class="text-button" data-fix-job="${job.id}">Risolvi</button>`:""}${resumable?`<button class="text-button" data-resume-job="${job.id}">Riprendi</button>`:""}${job.status!=="completed"?`<button class="text-button is-destructive" data-cancel-job="${job.id}">Annulla</button>`:""}</div></article>`}).join(""):`<p class="empty-message">Non ci sono ancora lavorazioni.</p>`}
function renderActivity(){const items=appState?.activity??[];$("activityList").innerHTML=items.length?items.map(x=>`<div class="activity-item is-${x.tone}"><time>${fmtTime(x.at)}</time><i></i><p>${esc(x.message)}</p></div>`).join(""):`<p class="empty-message">Qui compariranno le operazioni svolte.</p>`}
function renderSoftwareUpdate(){const state=appState?.softwareUpdate??{status:"unavailable",currentVersion:appState?.version,message:"Controllo non disponibile",percent:null};const active=Boolean(appState?.active);let action="check",label="Controlla adesso",disabled=false;if(state.status==="checking"){label="Controllo in corso…";disabled=true}else if(state.status==="available"){action="download";label=active?"Termina prima il lavoro":`Scarica v${state.availableVersion}`;disabled=active}else if(state.status==="downloading"){action="download";label=`Scaricamento ${Math.round(state.percent??0)}%`;disabled=true}else if(state.status==="downloaded"){action="install";label=active?"Termina prima il lavoro":"Installa e riavvia";disabled=active}else if(state.status==="unavailable"){label="Solo nell’app installata";disabled=true}else if(state.status==="up_to_date"){label="Controlla di nuovo"}else if(state.status==="error"){label="Riprova il controllo"}const title=state.status==="available"?`Versione ${state.availableVersion} disponibile`:state.status==="downloaded"?"Aggiornamento pronto":state.status==="up_to_date"?`Versione ${state.currentVersion} aggiornata`:"Aggiornamenti del programma";$("softwareUpdateTitle").textContent=title;$("softwareUpdateMessage").textContent=state.message;const progress=$("softwareUpdateProgress");progress.classList.toggle("is-hidden",state.status!=="downloading");progress.querySelector("span").style.width=`${Math.max(0,Math.min(100,state.percent??0))}%`;const settingsButton=$("softwareUpdateAction");settingsButton.dataset.updateAction=action;settingsButton.textContent=label;settingsButton.disabled=disabled;settingsButton.className=`button ${["available","downloaded"].includes(state.status)?"primary":"secondary"}`;const headerButton=$("updateButton");headerButton.dataset.updateAction=action;headerButton.textContent=state.status==="available"?`Aggiorna a v${state.availableVersion}`:state.status==="downloaded"?"Installa aggiornamento":state.status==="downloading"?`${Math.round(state.percent??0)}% scaricato`:state.status==="up_to_date"?"Programma aggiornato":"Controlla aggiornamenti";headerButton.disabled=disabled;headerButton.className=`button ${["available","downloaded"].includes(state.status)?"primary":"secondary"}`}
function renderReview(){const dialog=$("acquisitionReviewDialog"),review=appState?.prompt?.kind==="acquisition-review"?appState.prompt.review:null;if(!review){if(dialog.open)dialog.close();return}$("acquisitionReviewContext").textContent=[review.municipality,review.street,review.civicNumber].filter(Boolean).join(" · ")||"Risultati acquisiti";$("acquisitionReviewCount").textContent=`${review.properties.length} immobili`;$("acquisitionReviewContent").innerHTML=review.properties.map((p,i)=>`<article class="review-property"><section class="review-property-data"><p class="eyebrow">Immobile ${i+1}</p><h3>${esc(p.address??"Indirizzo non disponibile")}</h3><p>${esc(p.cadastralKey)}</p><dl><div><dt>Categoria</dt><dd>${esc(p.category??"—")}</dd></div><div><dt>Classe</dt><dd>${esc(p.class??"—")}</dd></div><div><dt>Consistenza</dt><dd>${esc(p.consistency??"—")}</dd></div><div><dt>Rendita</dt><dd>${p.cadastralIncome==null?"—":new Intl.NumberFormat("it-IT",{style:"currency",currency:"EUR"}).format(p.cadastralIncome)}</dd></div></dl></section><section class="review-owners"><p class="eyebrow">${p.owners.length} proprietari</p>${p.owners.map(o=>`<div class="review-owner"><div><strong>${esc(o.fullName)}</strong><small>${esc(o.taxCode??"CF mancante")}</small></div><div><span>${esc([o.birthPlace,o.birthDate].filter(Boolean).join(" · ")||"Nascita non disponibile")}</span><b>${o.sharePercentage==null?"Quota n/d":`${new Intl.NumberFormat("it-IT").format(o.sharePercentage)}%`}</b></div></div>`).join("")||"Nessun proprietario"}</section></article>`).join("");if(!dialog.open)dialog.showModal()}

function input(name,label,value,type="text"){return`<label class="manual-field">${esc(label)}<input name="${esc(name)}" type="${type}" value="${esc(value??"")}" /></label>`}
function renderCorrections(){const panel=$("manualCorrectionPanel"),container=$("manualCorrectionFields");if(!resolutionDetail){container.innerHTML=`<p class="empty-message">Apri una lavorazione per vedere i dati correggibili.</p>`;return}const props=resolutionDetail.properties??[],people=resolutionDetail.people??[];container.innerHTML=`${props.map(p=>`<section class="manual-entity" data-property-id="${p.id}"><h3>${esc(p.address??"Immobile senza indirizzo")}</h3><small>Compila sempre foglio, particella, subalterno e categoria.</small><div class="manual-grid">${input("sheet","Foglio",p.sheet)}${input("parcel","Particella",p.parcel)}${input("subaltern","Subalterno",p.subaltern)}${input("category","Categoria",p.category)}${input("address","Indirizzo",p.address)}${input("class","Classe",p.class)}${input("consistency","Consistenza",p.consistency)}${input("cadastralIncome","Rendita",p.cadastral_income,"number")}</div></section>`).join("")}${people.map(p=>`<section class="manual-entity" data-person-id="${p.id}"><h3>${esc(p.full_name)}</h3><small>Controlla soprattutto codice fiscale e quota.</small><div class="manual-grid">${input("fullName","Nome completo",p.full_name)}${input("taxCode","Codice fiscale",p.tax_code)}${input("birthPlace","Luogo di nascita",p.birth_place)}${input("birthProvince","Provincia",p.birth_province)}${input("birthDate","Data di nascita",p.birth_date,"date")}${input("shareOriginal","Quota originale",p.share_original)}${input("sharePercentage","Quota percentuale",p.share_percentage,"number")}</div></section>`).join("")}`;panel.classList.remove("is-hidden")}
async function loadResolution(jobId,show=true){resolutionJobId=jobId;resolutionDetail=await window.propertyWorker.getJobDetails(jobId);if(show){renderCorrections();$("manualCorrectionPanel").scrollIntoView({behavior:"smooth",block:"start"})}}
function nullableNumber(value){return value.trim()===""?null:Number(value.replace(",","."))}

function render(){if(!appState)return;selectedMode=appState.preferences?.mode??selectedMode;document.querySelectorAll("[data-mode]").forEach(b=>b.classList.toggle("is-selected",b.dataset.mode===selectedMode));$("modeHelp").textContent=selectedMode==="automatic"?"Procede da solo e si ferma solo quando non può scegliere in sicurezza.":"Ti chiede conferma prima dei salvataggi.";$("dryRunToggle").checked=appState.preferences?.dryRun!==false;$("versionLabel").textContent=`v${appState.version}`;$("excelPath").textContent=appState.config?.contactsExcelPath??appState.preferences?.contactsExcelPath??"Nessun file selezionato";$("screenshotPath").textContent=appState.config?.screenshotDirectory??"Gestito automaticamente";$("keepAliveStatus").textContent=appState.sisterKeepAlive?.statusLabel==="active"?`Attivo · ultimo controllo ${fmtTime(appState.sisterKeepAlive.checkedAt)}`:appState.sisterKeepAlive?.message??"In attesa";$("configurationStatus").textContent=appState.configError?"Da completare":appState.config?.configurationSource??"Pronta";$("configurationStatus").className=`status-pill ${appState.configError?"is-error":"is-complete"}`;$("startButton").disabled=appState.active||Boolean(appState.configError)||Boolean(appState.lastError&&appState.activeJobId);$("runBadge").className=`status-pill ${appState.active?"is-running":appState.lastError?"is-error":appState.currentStep==="completed"?"is-complete":"is-idle"}`;$("runBadge").innerHTML=`<span></span>${appState.active?"In lavorazione":appState.lastError?"Serve attenzione":appState.currentStep==="completed"?"Completata":"Pronto"}`;$("operationTitle").textContent=appState.active?guide(appState.currentStep).label:"Percorso completo";renderChecks();renderSteps();renderAction();renderJobs();renderActivity();renderReview();renderSoftwareUpdate()}
async function runChecks(){$("checkButton").disabled=true;$("lastCheckLabel").textContent="Sto controllando…";try{checks=await window.propertyWorker.runChecks();const ok=checks.every(x=>x.ok);$("lastCheckLabel").textContent=ok?"Tutto pronto":"Controlla gli elementi rossi";renderChecks();toast(ok?"Tutto pronto per partire":"Ci sono collegamenti da sistemare")}catch(e){toast(e.message??String(e))}finally{$("checkButton").disabled=false}}
function openCancel(jobId){if(!jobId)return;pendingCancelJobId=jobId;cancelInFlight=false;const d=$("cancelProcessDialog");d.querySelectorAll("button").forEach(b=>b.disabled=false);d.showModal()}

document.addEventListener("click",async event=>{const target=event.target.closest("button");if(!target)return;try{
  if(target.dataset.updateAction==="check")await window.propertyWorker.checkUpdate();
  else if(target.dataset.updateAction==="download")await window.propertyWorker.downloadUpdate();
  else if(target.dataset.updateAction==="install")await window.propertyWorker.installUpdate();
  else if(target.dataset.scroll)document.getElementById(target.dataset.scroll)?.scrollIntoView({behavior:"smooth"});
  else if(target.dataset.mode){selectedMode=target.dataset.mode;await window.propertyWorker.savePreferences({mode:selectedMode})}
  else if(target.id==="checkButton"||target.dataset.action==="checks")await runChecks();
  else if(target.id==="chromeButton"){await window.propertyWorker.openChrome();toast("Chrome di lavoro aperto")}
  else if(target.id==="chooseExcelButton"){const path=await window.propertyWorker.chooseExcel();if(path)toast("File Excel aggiornato")}
  else if(target.id==="startButton")await window.propertyWorker.startJob({mode:selectedMode,dryRun:$("dryRunToggle").checked});
  else if(target.dataset.action==="pause")await window.propertyWorker.pauseJob();
  else if(target.dataset.action==="resume-current"&&appState.activeJobId)await window.propertyWorker.resumeJob(appState.activeJobId);
  else if(target.dataset.resumeJob)await window.propertyWorker.resumeJob(target.dataset.resumeJob);
  else if(target.dataset.fixJob)await loadResolution(target.dataset.fixJob);
  else if(target.dataset.action==="open-corrections"&&appState.activeJobId)await loadResolution(appState.activeJobId);
  else if(target.dataset.action==="close-corrections")$("manualCorrectionPanel").classList.add("is-hidden");
  else if(target.dataset.action==="config"){document.getElementById("advancedConfiguration").open=true;document.getElementById("settings").scrollIntoView({behavior:"smooth"})}
  else if(target.dataset.action==="open-review")renderReview();
  else if(target.dataset.reviewDecision&&appState?.prompt){$("acquisitionReviewDialog").close();await window.propertyWorker.answerPrompt({promptId:appState.prompt.id,decision:target.dataset.reviewDecision})}
  else if(target.dataset.prompt&&appState?.prompt)await window.propertyWorker.answerPrompt({promptId:appState.prompt.id,decision:target.dataset.prompt==="confirm"&&["acquisition","manual"].includes(appState.prompt.kind)?undefined:target.dataset.prompt});
  else if(target.dataset.detailJob){const detail=await window.propertyWorker.getJobDetails(target.dataset.detailJob);$("detailPanel").classList.remove("is-hidden");$("detailContent").innerHTML=`<p><b>${detail.properties.length}</b> immobili · <b>${detail.people.length}</b> proprietari · <b>${detail.ownerships.length}</b> quote</p>${detail.properties.map(p=>`<div class="detail-group"><b>${esc(p.address??p.cadastral_key)}</b><small>${esc(p.cadastral_key)} · ${esc(p.processing_status)}</small></div>`).join("")}`;$("detailPanel").scrollIntoView({behavior:"smooth"})}
  else if(target.dataset.action==="close-detail")$("detailPanel").classList.add("is-hidden");
  else if(target.dataset.cancelJob)openCancel(target.dataset.cancelJob);
  else if(target.dataset.action==="cancel-current")openCancel(appState.activeJobId);
  else if(target.dataset.cancelDialog==="close"&&!cancelInFlight)$("cancelProcessDialog").close();
  else if(target.dataset.cancelDialog==="confirm"&&pendingCancelJobId){cancelInFlight=true;$("cancelProcessDialog").querySelectorAll("button").forEach(b=>b.disabled=true);await window.propertyWorker.cancelJob(pendingCancelJobId);$("cancelProcessDialog").close();toast("Lavorazione annullata")}
}catch(e){toast(e.message??String(e))}});

$("manualCorrectionForm").addEventListener("submit",async event=>{event.preventDefault();if(!resolutionDetail||!resolutionJobId)return;const properties=[...event.currentTarget.querySelectorAll("[data-property-id]")].map(section=>({id:section.dataset.propertyId,sheet:section.querySelector('[name="sheet"]').value,parcel:section.querySelector('[name="parcel"]').value,subaltern:section.querySelector('[name="subaltern"]').value,category:section.querySelector('[name="category"]').value,address:section.querySelector('[name="address"]').value||null,class:section.querySelector('[name="class"]').value||null,consistency:section.querySelector('[name="consistency"]').value||null,cadastralIncome:nullableNumber(section.querySelector('[name="cadastralIncome"]').value)}));const people=[...event.currentTarget.querySelectorAll("[data-person-id]")].map(section=>({id:section.dataset.personId,fullName:section.querySelector('[name="fullName"]').value,taxCode:section.querySelector('[name="taxCode"]').value||null,birthPlace:section.querySelector('[name="birthPlace"]').value||null,birthProvince:section.querySelector('[name="birthProvince"]').value||null,birthDate:section.querySelector('[name="birthDate"]').value||null,shareOriginal:section.querySelector('[name="shareOriginal"]').value,sharePercentage:nullableNumber(section.querySelector('[name="sharePercentage"]').value)}));try{await window.propertyWorker.saveManualCorrections({jobId:resolutionJobId,properties,people});$("manualCorrectionPanel").classList.add("is-hidden");toast("Correzioni salvate. Ora puoi riprendere il lavoro.")}catch(e){toast(e.message??String(e))}});
$("configurationForm").addEventListener("submit",async event=>{event.preventDefault();const data=new FormData(event.currentTarget);try{await window.propertyWorker.saveInternalConfiguration(Object.fromEntries(data));event.currentTarget.querySelector('[name="serviceRoleKey"]').value="";toast("Configurazione salvata e protetta") }catch(e){toast(e.message??String(e))}});
window.propertyWorker.onState(async state=>{appState=state;render();if(state.lastError&&state.activeJobId&&resolutionJobId!==state.activeJobId){try{await loadResolution(state.activeJobId,false)}catch{resolutionDetail=null}}});
window.propertyWorker.getState().then(async state=>{appState=state;render();if(state.lastError&&state.activeJobId)try{await loadResolution(state.activeJobId,false)}catch{resolutionDetail=null}}).catch(e=>toast(e.message??String(e)));
