-- Property Worker Import V2: independent, restartable per-property checkpoints.
-- The acquired SISTER graph remains the input; no V1 import state is reused.

create table if not exists public.property_worker_import_v2_items (
  id uuid primary key default gen_random_uuid(),
  job_id uuid not null references public.property_worker_jobs(id) on delete cascade,
  property_id uuid not null references public.property_worker_properties(id) on delete cascade,
  plan_fingerprint text,
  stage text not null default 'queued' check (stage in (
    'queued', 'planned', 'people_resolved', 'people_synced',
    'property_resolved', 'property_synced', 'ownerships_synced',
    'verified', 'activity_synced', 'completed'
  )),
  status text not null default 'queued' check (status in (
    'queued', 'running', 'quarantined', 'paused', 'completed'
  )),
  plan jsonb,
  checkpoint jsonb not null default '{}'::jsonb,
  attempts integer not null default 0 check (attempts >= 0),
  next_attempt_at timestamptz,
  last_error jsonb,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (property_id)
);

create index if not exists property_worker_import_v2_items_job_status_idx
  on public.property_worker_import_v2_items (job_id, status, updated_at);

create table if not exists public.property_worker_import_v2_events (
  id bigint generated by default as identity primary key,
  item_id uuid not null references public.property_worker_import_v2_items(id) on delete cascade,
  job_id uuid not null references public.property_worker_jobs(id) on delete cascade,
  property_id uuid not null references public.property_worker_properties(id) on delete cascade,
  stage text not null,
  event_name text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists property_worker_import_v2_events_item_idx
  on public.property_worker_import_v2_events (item_id, created_at);

drop trigger if exists set_property_worker_import_v2_items_updated_at on public.property_worker_import_v2_items;
create trigger set_property_worker_import_v2_items_updated_at
before update on public.property_worker_import_v2_items
for each row execute function public.set_updated_at();

alter table public.property_worker_import_v2_items enable row level security;
alter table public.property_worker_import_v2_events enable row level security;

do $$
declare
  table_name text;
  operation text;
begin
  foreach table_name in array array[
    'property_worker_import_v2_items', 'property_worker_import_v2_events'
  ] loop
    foreach operation in array array['select', 'insert', 'update', 'delete'] loop
      execute format('drop policy if exists %I on public.%I',
        'authenticated ' || operation || ' ' || table_name, table_name);
      if operation = 'insert' then
        execute format('create policy %I on public.%I for insert to authenticated with check (true)',
          'authenticated insert ' || table_name, table_name);
      elsif operation = 'update' then
        execute format('create policy %I on public.%I for update to authenticated using (true) with check (true)',
          'authenticated update ' || table_name, table_name);
      else
        execute format('create policy %I on public.%I for %s to authenticated using (true)',
          'authenticated ' || operation || ' ' || table_name, table_name, operation);
      end if;
    end loop;
  end loop;
end $$;
